#!/bin/bash

echoerr() { cat <<< "$@" 1>&2; }


if (( $# != 1 )); then
    echoerr "
Usage:

  update-smaai5-snapshot BASEDIR

try './scripts/update-smaai5-snapshot .'
"
	exit -1
fi

get_srcrev() {
    repo=$1
    branch=$2

    srcuri=git@bitbucket.org:inobram/$repo.git

    git ls-remote $srcuri | egrep "\s*refs/heads/$branch$" | awk '{ print $1 }'
}

record_srcrev() {
    recipe=$1
    repo=$2
    branch=$3
    output=$base/conf/smaai5-srcrev.conf
    srcrev=`get_srcrev $repo $branch`

	echoerr "updating recipe $recipe to use srcrev $srcrev"
    echo "$recipe 1 $srcrev" >> $output
}

commit_srcrev() {
	output=$base/conf/smaai5-srcrev.conf

	stanza=""
	while read -r line; do
		stanza="$stanza\n`echo "$line" | sed "s, 1 ,\t,g"`"
	done < <(git diff $output | grep -E '^[-+][a-z0-9]')

	git commit $output -s -m "$(echo -e "`basename $output`: Update revisions\n\nThe updates made are:\n\n$stanza")"
}

base=$1

echo "" > $base/conf/smaai5-srcrev.conf

#    cmd          recipe            repository         branch
record_srcrev     adc               adc                master
record_srcrev     airflow           airflow            modbus-v2.0
record_srcrev     alarm             alarm              modbus-v2.0
record_srcrev     buzzer            buzzer             master
record_srcrev     co2               co2                master
record_srcrev     curtain           curtain            master
record_srcrev     disarm            disarm             master
record_srcrev     display           display            modbus-v2.0
record_srcrev     exhauster         exhauster          master
record_srcrev     heater            heater             master
record_srcrev     hooter            hooter             master
record_srcrev     hour              hour               master
record_srcrev     inlet             inlet              master
record_srcrev     inverter          inverter           master
record_srcrev     lot               lot                master
record_srcrev     modbus            modbus             modbus-v2.0
record_srcrev     nebulizer         nebulizer          master
record_srcrev     ngrok             ngrok              master
record_srcrev     poweroff          poweroff           master
record_srcrev     probe             probe              master
record_srcrev     reading           reading            master
record_srcrev     relay             relay              master
record_srcrev     report-alarm      report-alarm       master
record_srcrev     rtc               rtc                master
record_srcrev     scale             scale              master
record_srcrev     sensation         sensation          master
record_srcrev     setting           setting            master
record_srcrev     statistic         statistic          master
record_srcrev     stick             stick              master
record_srcrev     synchronizer      synchronizer       master
record_srcrev     timer             timer              master
record_srcrev     updatebystick     updatebystick      master
record_srcrev     web               web                master
record_srcrev     watcher           watcher            master

sed -i '1{/^$/d}' $base/conf/smaai5-srcrev.conf

commit_srcrev
