#!/bin/bash

echoerr() { cat <<< "$@" 1>&2; }


if (( $# != 1 )); then
    echoerr "
Usage:

  update-inobram-snapshot BASEDIR

try './scripts/update-inobram-snapshot .'
"
	exit -1
fi

get_srcrev() {
    repo=$1
    branch=$2

    srcuri=git@bitbucket.org:inobram/$repo.git

    git ls-remote $srcuri | egrep "\s*refs/heads/$branch$" | awk '{ print $1 }'
}

record_srcrev() {
    recipe=$1
    repo=$2
    branch=$3
    output=$base/conf/inobram-srcrev.conf
    srcrev=`get_srcrev $repo $branch`

	echoerr "updating recipe $recipe to use srcrev $srcrev"
    echo "$recipe 1 $srcrev" >> $output
}

commit_srcrev() {
	output=$base/conf/inobram-srcrev.conf

	stanza=""
	while read -r line; do
		stanza="$stanza\n`echo "$line" | sed "s, 1 ,\t,g"`"
	done < <(git diff $output | grep -E '^[-+][a-z0-9]')

	git commit $output -s -m "$(echo -e "`basename $output`: Update revisions\n\nThe updates made are:\n\n$stanza")"
}

base=$1

echo "" > $base/conf/inobram-srcrev.conf

#    cmd          recipe            repository         branch
record_srcrev     actuators         actuators          master
record_srcrev     adc               adc                master
record_srcrev     airflow           airflow            master
record_srcrev     alarm             alarm              master
record_srcrev     ambientte-api     ambientte-api      master
record_srcrev     ambientte-display display_QT         master
record_srcrev     batch             batch              master
record_srcrev     buzzer            buzzer             master
record_srcrev     co2               co2                master
record_srcrev     curtain           curtain            master
record_srcrev     device-manager    device-manager     master
record_srcrev     disarm            disarm             master
record_srcrev     exhauster         exhauster          master
record_srcrev     flush             flush              master
record_srcrev     heater            heater             master
record_srcrev     hooter            hooter             master
record_srcrev     hour              hour               master
record_srcrev     humidifier        humidifier         master
record_srcrev     inlet             inlet              master
record_srcrev     inverter          inverter           master
record_srcrev     lot               lot                master
record_srcrev     modbusfans        modbusfans         master
record_srcrev     module4to20       module4to20        master
record_srcrev     nebulizer         nebulizer          master
record_srcrev     ngrok             ngrok              master
record_srcrev     power-manager     power-manager      master
record_srcrev     poweroff          poweroff           master
record_srcrev     probe             probe              master
record_srcrev     product-manager   product-manager    master
record_srcrev     reading           reading            master
record_srcrev     relay             relay              master
record_srcrev     relay8r           relay8r            master
record_srcrev     report-alarm      report-alarm       master
record_srcrev     scale             scale              master
record_srcrev     sensation         sensation          master
record_srcrev     services-supervisor services-supervisor master
record_srcrev     setting           setting            master
record_srcrev     settings          settings           master
record_srcrev     smaai5-display    display            master
record_srcrev     statistic         statistic          master
record_srcrev     synchronizer      synchronizer       master
record_srcrev     timer             timer              master
record_srcrev     tunneldoor        tunneldoor         master
record_srcrev     watcher           watcher            master
record_srcrev     web               web-smaai5         master
record_srcrev     web-n-pro         web-n-pro          master
record_srcrev     inobramlibs       inobramlibs        master
record_srcrev     usb-manager       usb-manager        master
record_srcrev     ambientte-display-validation         htmg-test-screen          master
record_srcrev     update-manager    update-manager     master

sed -i '1{/^$/d}' $base/conf/inobram-srcrev.conf

commit_srcrev
