#!/bin/bash

echoerr() { cat <<< "$@" 1>&2; }


if (( $# != 1 )); then
    echoerr "
Usage:

  update-smaai5-snapshot BASEDIR

try './scripts/update-smaai5-snapshot .'
"
	exit -1
fi

get_srcrev() {
    repo=$1
    branch=$2

    srcuri=git@bitbucket.org:inobram/$repo.git

    git ls-remote $srcuri | egrep "\s*refs/heads/$branch$" | awk '{ print $1 }'
}

record_srcrev() {
    recipe=$1
    repo=$2
    branch=$3
    output=$base/conf/smaai5-srcrev.conf
    srcrev=`get_srcrev $repo $branch`

	echoerr "updating recipe $recipe to use srcrev $srcrev"
    echo "$recipe 1 $srcrev" >> $output
}

commit_srcrev() {
	output=$base/conf/smaai5-srcrev.conf

	stanza=""
	while read -r line; do
		stanza="$stanza\n`echo "$line" | sed "s, 1 ,\t,g"`"
	done < <(git diff $output | grep -E '^[-+][a-z0-9]')

	git commit $output -s -m "$(echo -e "`basename $output`: Update revisions\n\nThe updates made are:\n\n$stanza")"
}

base=$1

echo "" > $base/conf/smaai5-srcrev.conf

#    cmd          recipe            repository         branch
record_srcrev     adc               adc                5.x
record_srcrev     airflow           airflow            5.x
record_srcrev     alarm             alarm              5.x
record_srcrev     buzzer            buzzer             5.x
record_srcrev     co2               co2                5.x
record_srcrev     curtain           curtain            5.x
record_srcrev     disarm            disarm             5.x
record_srcrev     display           display            5.x
record_srcrev     exhauster         exhauster          5.x
record_srcrev     heater            heater             5.x
record_srcrev     hooter            hooter             5.x
record_srcrev     hour              hour               5.x
record_srcrev     inlet             inlet              5.x
record_srcrev     inverter          inverter           5.x
record_srcrev     lot               lot                5.x
record_srcrev     nebulizer         nebulizer          5.x
record_srcrev     ngrok             ngrok              5.x
record_srcrev     poweroff          poweroff           5.x
record_srcrev     probe             probe              5.x
record_srcrev     reading           reading            5.x
record_srcrev     relay             relay              5.x
record_srcrev     report-alarm      report-alarm       5.x
record_srcrev     rtc               rtc                5.x
record_srcrev     scale             scale              5.x
record_srcrev     sensation         sensation          5.x
record_srcrev     setting           setting            5.x
record_srcrev     statistic         statistic          5.x
record_srcrev     stick             stick              5.x
record_srcrev     synchronizer      synchronizer       5.x
record_srcrev     timer             timer              5.x
record_srcrev     updatebystick     updatebystick      5.x
record_srcrev     web               web                5.x

sed -i '1{/^$/d}' $base/conf/smaai5-srcrev.conf

commit_srcrev
