#!/bin/sh
# -*- shell-script -*-
set -e

EMMC="/dev/mmcblk1"

set_leds() {
    if [ -e /sys/class/leds/beaglebone\:green\:usr0/trigger ] ; then
        echo $1 > /sys/class/leds/beaglebone\:green\:usr0/trigger
        echo $1 > /sys/class/leds/beaglebone\:green\:usr1/trigger
        echo $1 > /sys/class/leds/beaglebone\:green\:usr2/trigger
        echo $1 > /sys/class/leds/beaglebone\:green\:usr3/trigger
    fi
}


die() {
    set_leds none
    while true; do
        sleep 1
    done
}


run_install() {
    set_leds heartbeat || die
    cd /installer-data || die
    bmaptool copy img.wic.xz "$EMMC" || die
}

if run_install ; then
    set_leds default-on
else
    die
fi
